### ISSUE TITLE
chk command not working

### ISSUE THREAD

**Issue by binhosouzaalmeida0** [xbinner18/ccchk-ub#15]
[ERROR/2023-11-02 22:26:19,721] telethon.client.updates: Unhandled exception on st_charge
Traceback (most recent call last):
  File "C:\Users\joaozera\AppData\Roaming\Python\Python310\site-packages\telethon\client\updates.py", line 570, in _dispatch_update
    await callback(event)
  File "C:\Users\joaozera\Desktop\BOT CHK PYTHON - V5\ubb\modules\chk.py", line 67, in st_charge
    Id = resq.json()['id']
KeyError: 'id'

**Comment by xbinner18** [comment]
Site is dead
